/* Generated by Together */

package com.ldtec.base.DB;

import com.ldtec.utils.DBCP.ConnectionManager;
import com.ldtec.utils.DBCP.ConnectionPool;
/** 从连接池中获取连接 */
public class GetDbPool {
//  private ConnectionManager FManager;
    private ConnectionPool EduPool = null;

    public GetDbPool(String poolConfig) {
        try {
            ConnectionManager.init(poolConfig);
        } catch (Exception et) {
            System.out.println("Load Connection Manager Error");
        }
    }

    /** @return 取得公共库的连接池; */
    public ConnectionPool getDbPool(String dbName) {
        try {
            EduPool = ConnectionManager.getConnectionPool(dbName);
        } catch (Exception et) {
            System.out.println("Can't get " + dbName + " connectiol pool");
        }
        return EduPool;
    }

    private void debug(String result) {
        System.out.println("come from " + result);
    }
}
